# Generated by Django 4.1.7 on 2023-03-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckListItem',
        ),
    ]
